name: Triggers

on:
 pull_request:
  types:
   - opened
  branches:
   - master
jobs:
 echo-triggers:
  runs-on: windows-latest
  steps: 
   - name: Window platform
     shell: bash
     run: echo "Windows platform"
